kind: Secret
metadata:
  name: aws-secret
  namespace: crossplane-system
type: Opaque
apiVersion: v1
data:
  creds: W2RlZmF1bHRdCmF3c19hY2Nlc3Nfa2V5X2lkID0gQUtJQVlCV0tOWjZETVAyRUlBSE8KYXdzX3NlY3JldF9hY2Nlc3Nfa2V5ID0gTkFnS1ZWbU05ZEtxNVY1TXo4bXdjTlcweEtXUEZ6VWk1QkJsSGF2SA==