apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-sa
  namespace: test-ns
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::553401569158:role/my-secret-role

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-cluster-sa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::553401569158:role/my-secret-cluster-role