apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: aws-config
  annotations:
    eks.amazonaws.com/role-arn:
    argocd.argoproj.io/sync-wave:
    argocd.argoproj.io/sync-options: 

    