apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-environment-configs
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "5" # Sync after XRD
spec:
  package: xpkg.upbound.io/crossplane-contrib/function-environment-configs:v0.0.5