apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-patch-and-transform
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "5" # Sync after XRD
spec:
  package: xpkg.upbound.io/crossplane-contrib/function-patch-and-transform:v0.4.0